endpoints:
  metrics:
    sensitive: false
management:
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 8095
spring:
  security:
    user:
      name: admin
      password: admin
springdoc:
  swagger-ui:
    path: /api/v1/help
    disable-swagger-default-url: true
  api-docs:
    path: /api/v1/docs/api-docs

